## CSCI-467 Discussion (Week 1)

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [18]:
import pandas as pd
salary_data = pd.read_csv("Salaries.csv", sep=",", index_col=3, header=0, skiprows=[1])
salary_data

yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [21]:
players = salary_data.loc[(salary_data['salary'] > 1000000) & (salary_data['teamID'].isin(["ATL","HOU"])) ]
players
# players = players.loc[players['teamID'].isin(["ATL","HOU"])]
# players.head(10);
# print(players.index);


yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[595 rows x 4 columns]

#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [25]:
salaryATL = salary_data.loc[salary_data['teamID'] == 'ATL']
print(salaryATL['salary'].describe())


count    8.860000e+02
mean     2.206239e+06
std      3.432673e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.390625e+06
max      1.606180e+07
Name: salary, dtype: float64


#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [30]:
newDict= salary_data.to_dict('list')
newDict

{'yearID': [1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985,
  1985

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

In [42]:
df = pd.DataFrame(newDict, index = salary_data.index)
df.columns = ["a","b","c","d"]
df


a    b   c         d
playerID                          
barkele01  1985  ATL  NL    870000
bedrost01  1985  ATL  NL    550000
benedbr01  1985  ATL  NL    545000
campri01   1985  ATL  NL    633333
ceronri01  1985  ATL  NL    625000
...         ...  ...  ..       ...
treinbl01  2015  WAS  NL    512800
ugglada01  2015  WAS  NL    507500
werthja01  2015  WAS  NL  21000000
zimmejo02  2015  WAS  NL  16500000
zimmery01  2015  WAS  NL  14000000

[25575 rows x 4 columns]

### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [43]:
import numpy as np
TwoD = [[1,2,3],[4,5,6]];
npArray = np.array(TwoD);
npArray

array([[1, 2, 3],
       [4, 5, 6]])

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

In [49]:
print(npArray.ndim)
print(npArray.shape)
print(npArray.dtype.name)
print(npArray.itemsize)
print(npArray.size)
print(npArray.data)

2
(2, 3)
int64
8
6


#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

In [53]:
arr = np.arange(15).reshape(3,5)
ar1 = np.array(arr)
ar1.flatten()



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

In [56]:
ar1[2:, 2:5]

array([[12, 13, 14]])

#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

In [71]:
#position of max and min
print(ar1.argmax())
print(ar1.argmin())
#value
print(ar1.min())
print(ar1.mean())
print(ar1.std())
#product(inner product)
print(ar1.dot(2))
print(ar1.sum())
ar2 = np.array([1,3,5,7]);
print(np.square(ar1))
print(np.exp(ar2))
print(np.sign(ar1))
print(np.mod(ar1,3));

14
0
0
7.0
4.320493798938574
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
105
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[   2.71828183   20.08553692  148.4131591  1096.63315843]
[[0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 0 1]
 [2 0 1 2 0]
 [1 2 0 1 2]]


#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [85]:
ar3 = np.eye(4)
ar3 = ar3.astype('int32')
np.ones((2,2))
np.zeros((2,2))
# Two array
ar4 = np.array([[1,2,3],[3,2,1]])
ar5 = np.array([[1,2,5],[5,2,1]])
np.concatenate([ar4,ar5])
# Evenly distributed interval given the range
np.linspace(2.0, 4.0, num = 10, retstep=True)

(array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
        3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ]),
 0.2222222222222222)

### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.